export default function Head() {
	return (
		<>
			<title>Sign In</title>
			<meta name="description" content="Generated by create next app" />
			{/* <link rel="icon" href="/favicon.ico" /> */}
		</>
	)
}