export default function SignUpHead() {
	return (
		<>
			<title>Sign Up</title>
			<meta name="description" content="Generated by create next app" />
			{/* <link rel="icon" href="/favicon.ico" /> */}
		</>
	)
}